# Generated by Django 4.2.3 on 2023-08-01 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
