# Generated by Django 4.2.3 on 2023-08-01 17:18

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=test_app.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
