# Generated by Django 4.2.3 on 2023-08-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_room_vote_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='vote_queue',
        ),
    ]
